dist: bionic
language: minimal
env:
  global:
    - BASE_IMAGE=fedora:32
    - TEST_CMD="ruby ./test.rb"

.com.github.junaruga.report-rubygems-load-yaml.definitions:
  - &test_in_container
    install:
      - |
        travis_retry docker build --rm -t test/rubygems \
          -f ci/Dockerfile-fedora \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          .
    script:
      - |
        docker run --rm -t test/rubygems ${TEST_CMD}

jobs:
  include:
    - name: "Fedora rawhide Ruby 2.7"
      env:
        - BASE_IMAGE=fedora:rawhide
      <<: *test_in_container
    - name: "Fedora 32 Ruby 2.7"
      env:
        - BASE_IMAGE=fedora:32
      <<: *test_in_container
    - name: "Fedora 32 Ruby 2.6"
      env:
        - BASE_IMAGE=fedora:31
      <<: *test_in_container
  allow_failures:
    - name: "Fedora rawhide Ruby 2.7"
    - name: "Fedora 32 Ruby 2.7"
  fast_finish: true
branches:
  except:
    - /^wip\//
